In [1]:
import pandas as pd
import pathlib

In [5]:
path = 'C:\\Users\\aci_d\\Documents\\Desenvolvimento\\01_Fut\\documentos\\RAW\\02_AUX\\01_Serie_A_2016.txt'

In [2]:
cols = ['Equipe', '# J', 'Idade', 'Posse', 'MP',
       'Gols', 'Assis.', 'G-PB', 'PB', 'PT', 'CrtsA', 'CrtV', 'Gols.1',
       'Assis..1', 'G+A', 'G-PB.1', 'G+A-PB']

In [3]:
path_ = 'C:\\Users\\aci_d\\Documents\\Desenvolvimento\\01_Fut\\documentos\\'
path_folder = path_ + 'RAW\\02_AUX\\'

In [4]:
file_list = list(pathlib.Path(path_folder).glob("**/*txt"))

In [7]:
df = pd.DataFrame()
for file in file_list:
    df_comp = pd.read_csv(file, usecols=cols, sep = '\t')
    df_comp['ano'] = str(file).split('\\')[-1].split('_')[-1].replace('.txt','')
    df = df.append(df_comp)

df

,Equipe,# J,Idade,Posse,MP,Gols,Assis.,G-PB,PB,PT,CrtsA,CrtV,Gols.1,Assis..1,G+A,G-PB.1,G+A-PB,ano
0,América (MG),46,"27,2",45.3,38,23,17,21,2,3,68,3,"0,61","0,45","1,05","0,55","1,00",2016
1,Atl Paranaense,36,"24,8",48.6,38,37,24,33,4,4,76,1,"0,97","0,63","1,61","0,87","1,50",2016
2,Atlético Mineiro,39,"28,1",53.3,37,61,49,56,5,5,76,4,"1,65","1,32","2,97","1,51","2,84",2016
3,Botafogo (RJ),34,"26,6",48.3,38,43,31,38,5,6,94,2,"1,13","0,82","1,95","1,00","1,82",2016
4,Chapecoense,35,"27,8",46.2,37,47,30,40,7,7,78,2,"1,27","0,81","2,08","1,08","1,89",2016
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15,vs Ponte Preta,46,"27,0",46.9,38,39,27,34,5,6,94,11,"1,03","0,71","1,74","0,89","1,61",2019
16,vs São Bento,47,"27,0",48.1,38,53,29,48,5,8,105,4,"1,39","0,76","2,16","1,26","2,03",2019
17,vs Sport Recife,31,"26,9",47.1,38,28,20,24,4,6,89,6,"0,74","0,53","1,26","0,63","1,16",2019
18,vs Vila Nova,42,"27,0",51.6,38,40,26,38,2,2,88,1,"1,05","0,68","1,74","1,00","1,68",2019
19,vs Vitória,47,"27,2",51.9,38,45,32,41,4,4,102,4,"1,18","0,84","2,03","1,08","1,92",2019

In [10]:
df.loc[~df['Equipe'].str.contains('vs'),'info_type'] = 1
df.loc[df['Equipe'].str.contains('vs'),'info_type'] = 2
df['Equipe'] = df['Equipe'].astype(str).str.replace('vs ','',regex = True)
#df = df.rename(columns= dict_aux_file)
df

,Equipe,# J,Idade,Posse,MP,Gols,Assis.,G-PB,PB,PT,CrtsA,CrtV,Gols.1,Assis..1,G+A,G-PB.1,G+A-PB,info_type
0,América (MG),46,"27,2",45.3,38,23,17,21,2,3,68,3,"0,61","0,45","1,05","0,55","1,00",1.0
1,Atl Paranaense,36,"24,8",48.6,38,37,24,33,4,4,76,1,"0,97","0,63","1,61","0,87","1,50",1.0
2,Atlético Mineiro,39,"28,1",53.3,37,61,49,56,5,5,76,4,"1,65","1,32","2,97","1,51","2,84",1.0
3,Botafogo (RJ),34,"26,6",48.3,38,43,31,38,5,6,94,2,"1,13","0,82","1,95","1,00","1,82",1.0
4,Chapecoense,35,"27,8",46.2,37,47,30,40,7,7,78,2,"1,27","0,81","2,08","1,08","1,89",1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15,Ponte Preta,46,"27,0",46.9,38,39,27,34,5,6,94,11,"1,03","0,71","1,74","0,89","1,61",2.0
16,São Bento,47,"27,0",48.1,38,53,29,48,5,8,105,4,"1,39","0,76","2,16","1,26","2,03",2.0
17,Sport Recife,31,"26,9",47.1,38,28,20,24,4,6,89,6,"0,74","0,53","1,26","0,63","1,16",2.0
18,Vila Nova,42,"27,0",51.6,38,40,26,38,2,2,88,1,"1,05","0,68","1,74","1,00","1,68",2.0
19,Vitória,47,"27,2",51.9,38,45,32,41,4,4,102,4,"1,18","0,84","2,03","1,08","1,92",2.0

In [11]:
set(df['Equipe'].tolist())

{'ABC',
 'América (MG)',
 'Atl Goianiense',
 'Atl Paranaense',
 'Atlético Mineiro',
 'Avaí',
 'Bahia',
 'Boa',
 'Botafogo (RJ)',
 'Botafogo (SP)',
 'Bragantino',
 'Brasil (RS)',
 'Brasil de Pelotas',
 'CRB',
 'CSA',
 'Ceará',
 'Chapecoense',
 'Corinthians',
 'Coritiba',
 'Criciúma',
 'Cruzeiro',
 'Cuiabá',
 'Figueirense',
 'Flamengo',
 'Fluminense',
 'Fortaleza',
 'Goiás',
 'Grêmio',
 'Guarani',
 'Internacional',
 'Joinville',
 'Juventude',
 'Londrina',
 'Luverdense',
 'Náutico',
 'Oeste',
 'Operário',
 'Palmeiras',
 'Paraná',
 'Paysandu',
 'Ponte Preta',
 'Sampaio Corrêa',
 'Santa Cruz',
 'Santos',
 'Sport Recife',
 'São Bento',
 'São Paulo',
 'Tupi FC',
 'Vasco da Gama',
 'Vila Nova',
 'Vitória'}